backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: 'meta'
    label: 'Tags'
    delete: false
    editor:
      preview: false
    files:
      - name: 'authors'
        label: 'Authors'
        file: 'cms/meta/authors.json'
        description: 'Author descriptions'
        fields:
          - name: authors
            label: Authors
            label_singular: 'Author'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the author'
              - label: 'Name'
                name: 'name'
                widget: 'string'
                hint: 'First and Last'
              - label: 'Introduction'
                name: 'introduction'
                widget: 'text'
      - name: 'tags'
        label: 'Tags'
        file: 'cms/meta/tags.json'
        description: 'List of tags'
        fields:
          - name: tags
            label: Tags
            label_singular: 'Tag'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the tag'
              - label: 'Display Name'
                name: 'name'
                widget: 'string'
                hint: 'Tag name for displaying on the site'

  - name: 'team_members'
    label: 'Team Members'
    delete: false
    editor:
      preview: false
    files:
      - name: 'team_members'
        label: 'Team members'
        file: 'cms/meta/team_members.json'
        description: 'List of Ya! Magazine Team Members'
        fields:
          - name: members
            label: Members
            label_singular: 'Member'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the team members'
              - label: 'Name'
                name: 'name'
                widget: 'string'
                hint: 'Full name'
              - label: 'Avatar'
                name: 'avatar'
                widget: 'image'
                allow_multiple: false
              - label: 'Id'
                name: 'id'
                widget: 'string'
                hint: 'Unique Id'
              - label: 'Role'
                name: 'role'
                widget: 'string'
                hint: 'His/her role in the team'
              - label: 'Social Media'
                name: 'social_media'
                widget: 'list'
                summary: { { field. } }
                fields:
                  - { label: Instagram, name: instagram, widget: string }
                  - { label: Twitter, name: twitter, widget: string }
                  - { label: Email, name: email, widget: string }
                  - { label: Website, hint: 'Personal Website etc', name: website, widget: string }

  - name: 'posts'
    label: 'Blog Posts'
    folder: '/data/posts'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'string'
      - label: 'Featured Post'
        name: 'featuredpost'
        widget: 'boolean'
      - label: 'Featured Image'
        name: 'featuredimage'
        widget: 'image'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - label: Author
        name: 'author'
        widget: relation
        collection: 'meta'
        file: 'authors'
        searchFields:
          - 'authors.*.name'
        displayFields:
          - 'authors.*.name'
        valueField: 'authors.*.slug'
      - label: Tags
        label_singular: 'Tag'
        name: 'tags'
        widget: list
        summary: '{{fields.tag}}'
        field:
          label: Tag
          name: tag
          widget: relation
          collection: 'meta'
          file: 'post-tags'
          search_fields:
            - 'tags.*.name'
          display_fields:
            - 'tags.*.name'
          value_field: 'tags.*.slug'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

- name: 'gallery'
  label: 'Gallery Indorsagraphy'
  delete: false
  editor:
    preview: false
  files:
    - name: 'gallery'
      label: 'Gallery'
      file: 'cms/meta/gallery.json'
      description: 'Photos from Indorsagraphy'
      fields:
        - name: photos
          label: Photos
          label_singular: 'Photo'
          widget: list
          fields:
            - label: 'Slug'
              name: 'slug'
              widget: 'string'
              hint: 'The part of a URL identifies the photos name'
            - label: 'Owner'
              name: 'owner'
              widget: 'string'
              hint: 'Name of the photographer'
            - label: 'Photo'
              name: 'photo'
              widget: 'image'
              allow_multiple: false
            - label: 'Description'
              name: 'description'
              widget: 'string'
              hint: 'Description of the photo'

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - name: 'site'
        label: 'Site Settings'
        file: 'cms/site-settings.json'
        description: 'General site settings'
        fields:
          - label: 'URL'
            name: 'base_url'
            widget: 'string'
            hint: 'Do not enter the trailing slash of the URL'
          - label: 'Site title'
            name: 'site_title'
            widget: 'string'
          - label: 'Site description'
            name: 'site_description'
            widget: 'string'
          - label: 'Site keywords'
            name: 'site_keywords'
            widget: 'list'
            summary: '{{fields.keyword.keyword}}'
            field:
              label: Keyword
              name: keyword
              widget: 'string'
          - label: 'Posts per page'
            name: 'posts_per_page'
            widget: 'number'
            value_type: 'int'
            min: 1
            max: 30
            default: 9
          - label: 'Twitter account'
            name: 'twitter_account'
            widget: 'string'
          - label: 'Facebook account'
            name: 'facebook_account'
            widget: 'string'
          - label: 'Instagram account'
            name: 'instagram_account'
            widget: 'string'
          - label: 'Contact Email'
            name: 'contact_email'
            widget: 'string'
          - label: 'Contact Phonenumber'
            name: 'contact_phonenumber'
            widget: 'string'
          - label: 'Contact Address'
            name: 'contact_address'
            widget: 'string'
